### ISSUE TITLE
llvmlite installation fails for numba in python 3.5

### ISSUE THREAD

**Issue by koopmans92** [farmborst/sciduck#1]
istalling llvmlite version 0.27.0 manually works
see also: https://github.com/numba/llvmlite/issues/471

**Comment by farmborst** [comment]
Thanks for the info. Have just pushed a temporary solution to master by fixing the llvmlite version as suggested. This fix should become obsolete with the next release of numba (0.43) and llvmlite (0.28) according to this [comment](https://github.com/numba/llvmlite/issues/471#issuecomment-472413965) in the issue of llvmlite you linked.
